### ISSUE TITLE
Error installing 'ntbox' package

### ISSUE THREAD

**Issue by Dubults** [luismurao/ntbox#9] opened 2021-05-30 12:22 UTC
When trying to install 'ntbox', I get an error:
> if (!require('devtools')) install.packages('devtools')
> devtools::install_github('luismurao/ntbox')
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Roxyg ...' is malformed!

Both Rtools and Pandoc are installed on a Windows 10 64-bit machine. The R version is 4.0.2

**Comment by luismurao** [comment] 2021-06-01 01:12
Hello @Dubults 
Could you try installing ntbox with 
remotes::install_github("luismurao/ntbox")
Please could you tell me if it worked for you
Best
Luis

**Comment by Dubults** [comment] 2021-06-02 10:04
Thanks for the response!
Still no success:
> remotes::install_github("luismurao/ntbox")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Roxyg ...' is malformed!

best wishes
Ainars

**Comment by luismurao** [comment] 2021-06-02 16:13
Could you share your session info
sessioninfo::session_info()

**Comment by Dubults** [comment] 2021-06-02 16:17
Here it comes:
> sessioninfo::session_info()
- Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  Latvian_Latvia.1257         
 ctype    Latvian_Latvia.1257         
 tz       Europe/Helsinki             
 date     2021-06-02                  

- Packages -------------------------------------------------------------------
 package     * version date       lib source        
 cli           2.5.0   2021-04-26 [1] CRAN (R 4.0.2)
 curl          4.3.1   2021-04-30 [1] CRAN (R 4.0.5)
 remotes     * 2.3.0   2021-04-01 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.2)

[1] C:/Program Files/R/R-4.0.2/library
>

**Comment by luismurao** [comment] 2021-06-02 17:53
OK,
Thank you @Dubults I checked the issue on [stackoverflow](https://stackoverflow.com/questions/59332234/r-install-github-error-failed-to-install-unknown-package), although it is not exactly the same error, it seems that could work, so let's try it.
First restart your R session and then
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("luismurao/ntbox")

If it does not work let's do it in the old fashioned way:  

1.  Download de repo:
   - go to https://github.com/luismurao/ntbox and locate the green button that says "Code", download as zip
   - Unzip the repo and locate the folder path (**ntbox-master**)

2. Go to R, restart your session and install `ntbox` dependencies:
``` r
pkgs <- c('Rcpp','shiny','shinyFiles','rgeos','rgdal',
          'sp','raster','ncdf4','maptools','dismo','rgl',
          'dygraphs','leaflet','leaflet.extras','png',
          'ggplot2','XML','rmarkdown','knitr','stringr',
          'MASS','mgcv','googleVis','rasterVis','plyr',
          'shinyBS','shinyjs','rglwidget','car','maps',
          'corrplot','dplyr','cluster','fields',
          'devtools','psych','magrittr','shinythemes',
          'grid','RColorBrewer','scales','ade4','V8',
          'rio','future','furrr','stringi','purrr',
          'spocc','sdmpredictors')
install.packages(pkgs)
```
3. Restart R again and install `ntbox`
```r
install.packages("path_to_the/ntbox-master_folder",type="source", repos=NULL)
```

Let me know if it worked
All the best 
Luis

**Comment by Dubults** [comment] 2021-06-02 18:30
Thanks!
The 'old fashioned' option worked!
The first approach ended with the same error:
> Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
> remotes::install_github("luismurao/ntbox")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Roxyg ...' is malformed!
>

Thank you so much for finding the solution!
best wishes
Ainars

**Comment by luismurao** [comment] 2021-06-02 18:42
Great @Dubults !! 
I will close the issue since it seems that the problem is not related to `ntbox` by itself.
Best
Luis

**Closed by luismurao** 2021-06-02 18:42 UTC
